language: node_js
node_js:
  - '4.5'

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 5

before_script:
  - npm install -g bower
  - bower install
  - npm start

script:
  - npm run test-single-run
  - npm run protractor

after_script:
  - npm stop

notifications:
  email: false
