language: node_js
node_js:
  - '4.5'


before_script:
  - npm install -g bower
  - bower install
  - npm start
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/protractor/bin/install_selenium_standalone
  -  java -jar selenium/selenium-server-standalone-2.35.0.jar -Dwebdriver.chrome.driver=./selenium/chromedriver &
  - sleep 3

script:
  - npm run test-single-run
  - npm run protractor

after_script:
  - npm stop

notifications:
  email: false
