language: node_js
node_js:
  - '4.5'

before_script:
  - npm install -g bower
  - bower install
  - npm start

script:
  - npm run test-single-run
  - npm run protractor

after_script:
  - npm stop

notifications:
  email: false
